# GRPC Server.
grpc:
  address: ":9081"
  name: "gfcq_config"
  logPath: "/tmp/log/"
  logStdout: true
  errorStack: true
  errorLogEnabled: true
  errorLogPattern: "error-{Ymd}.log"
  accessLogEnabled: true
  accessLogPattern: "access-{Ymd}.log"
  etcdLink: "127.0.0.1:9081"
  organize:
    name: "organize"
    link: "127.0.0.1:9091"

# Global logging.
logger:
  level: "all"
  stdout: true
  logPath: "/tmp/log/"

# Database.
database:
  logger:
    level: "all"
    stdout: true

  default:
    link: "mysql:root:123456@tcp(127.0.0.1:3807)/cqgf_product?loc=Local"
    debug: true


