// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/lj1570693659/gfcq_config/internal/dao/internal"
)

// internalCrewKpiRuleDao is internal type for wrapping internal DAO implements.
type internalCrewKpiRuleDao = *internal.CrewKpiRuleDao

// crewKpiRuleDao is the data access object for table cqgf_crew_kpi_rule.
// You can define custom methods on it to extend its functionality as you wish.
type crewKpiRuleDao struct {
	internalCrewKpiRuleDao
}

var (
	// CrewKpiRule is globally public accessible object for table cqgf_crew_kpi_rule operations.
	CrewKpiRule = crewKpiRuleDao{
		internal.NewCrewKpiRuleDao(),
	}
)

// Fill with you ideas below.
